baseURL = "https://kqh.ac/"
title = "赫赫文王"
enableRobotsTXT = true
enableEmoji = true
theme = "jane"
disablePathToLower = true

hasCJKLanguage = true     # has chinese/japanese/korean ?
paginate = 15              # Number of articles displayed on the homepage
rssLimit = 5            # Limit Entry Count to Rss file
copyright = ""            # default: author.name ↓
uglyURLs = false         # more info: https://gohugo.io/content-management/urls/#ugly-urls

[blackfriday]
hrefTargetBlank = true

# Highlight options.
# See https://gohugo.io/content-management/syntax-highlighting/
pygmentsCodeFences = true # Enable syntax highlighting with GitHub flavoured code fences
PygmentsUseClasses = false # Use CSS classes to format highlighted code
PygmentsCodefencesGuessSyntax = true
PygmentsOptions = "linenos=inline"

# Enable author pages
[taxonomies]
 author = "author"
 tag = "tags"
 category = "categories"

defaultContentLanguage = "en"
[languages.en]
  languageCode = "en"

[author]                  # essential
  name = "柯棋瀚"

[sitemap]                 # essential
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

  [[menu.main]]
     name = "赫赫文王"
     weight = 10
     identifier = "archives"
     url = "/post/"
 [[menu.main]]
    name = "分類"
    weight = 20
    identifier = "categories"
    url = "/categories/"
  [[menu.main]]
   name = "系列"
   weight = 30
   identifier = "tags"
   url = "/tags/"
 [[menu.main]]
   name = "作者"
    weight = 40
    identifier = "author"
  url = "/author/"
   [[menu.main]]
     name = "維基"
      weight = 70
    url = "https://kqh.wiki/"
    [[menu.main]]
      name = "琴譜网"
       weight = 80
     url = "https://qinpu.wiki/"

[params]
  debug = false             # If true, load `eruda.min.js`. See https://github.com/liriliri/eruda
  since = "2017/10/03"            # Site creation time
  homeFullContent = false   # if false, show post summaries on home page. Othewise show full content.
  rssFullContent = true     # if false, Rss feed instead of the summary

  # site info (optional)                                  # 站点信息（可选，不需要的可以直接注释掉）
  logoTitle = "主&nbsp&nbsp&nbsp&nbsp葉"        # default: the title value
  keywords = ["古琴", "書法","錄音","經學","歷史"]
  description = "不務正業的歷史系學生一箇"

  # paginate of archives, tags and categories             # 归档、标签、分类每页显示的文章数目，建议修改为一个较大的值
  archive-paginate = 100

  # paginate style, default use numbered pagination links. if true, use original "Previous" and "Next" links.
  # paginateOriginalStyle = true

  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  dateFormatToUse = "2006-01-02"

  # show word count and read time ?                       # 是否显示字数统计与阅读时间
  moreMeta = true

  # show language chooser in menu
  showMenuLanguageChooser = false

  showAuthorInfo = true

  # 一些全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能，在 archetypes/default.md 查看更多信息。
  # Some global options, you can also close or open something in front matter for a single post, see more information from `archetypes/default.md`.
  toc = false                                                               # 是否开启目录
  photoswipe = true         # see https://github.com/dimsemenov/PhotoSwipe            # 是否启用PhotoSwipe（图片可点击）
  bootcdn = true           # In china. @Deprecated: use [params.publicCDN]             # 是否使用bootcdn(@Deprecated: 请使用[params.publicCDN])
  mathjax = false           # see https://www.mathjax.org/                              # 是否使用mathjax（数学公式）
  contentCopyright = '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh" target="_blank">CC BY-NC-SA 4.0</a>，非商業用途可隨意使用，但須遵守此協定'
  linkToMarkDown = true
  verticle = true

  baidu_push = true        # baidu push
  baidu_analytics = "557733f5e13d0e8e483604d851d79134"
  baidu_verification = "8qCdaqkmZt"   # Baidu Verification
# google_verification = ""  # Google_Verification
# googleAnalytics = ""      # UA-XXXXXXXX-X

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  customCSS = []            # if ['custom.css'], load '/static/css/custom.css' file
  customJS = []             # if ['custom.js'], load '/static/js/custom.js' file

  # enable 'fork me on github', see https://blog.github.com/2008-12-19-github-ribbons/
  # forkMeOnGithub = "https://github.com/xianmin/hugo-theme-jane"

  [params.publicCDN]        # load these files from public cdn                          # 启用公共CDN，需自行定义
    enable = true
    jquery = '<script src="https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>'
    slideout = '<script src="https://cdn.jsdelivr.net/npm/slideout@1.0.1/dist/slideout.min.js" integrity="sha256-t+zJ/g8/KXIJMjSVQdnibt4dlaDxc9zXr/9oNPeWqdg=" crossorigin="anonymous"></script>'
    gitmentJS = '<script src="https://cdn.jsdelivr.net/npm/gitment@0.0.3/dist/gitment.browser.min.js" crossorigin="anonymous"></script>'
    gitmentCSS = '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/gitment@0.0.3/style/default.min.css" crossorigin="anonymous">'
    photoswipe = '<script src="https://cdn.jsdelivr.net/npm/photoswipe@4.1.2/dist/photoswipe.min.js" integrity="sha256-iG1tiE5xJSJQhKdeOW4cPiSy+RTrnRKjjjrVQ0hexug=" crossorigin="anonymous"></script>'
    photoswipe-ui = '<script src="https://cdn.jsdelivr.net/npm/photoswipe@4.1.2/dist/photoswipe-ui-default.min.js" integrity="sha256-XvSk6Opq7XZ8oUcx213MtikXtbl5bbe4Q9tr4+NJBCg=" crossorigin="anonymous"></script>'
    photoswipeCSS = '<link src="https://cdn.jsdelivr.net/npm/photoswipe@4.1.2/dist/photoswipe.min.css" integrity="undefined" crossorigin="anonymous">'
    photoswipeSKIN = '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/photoswipe@4.1.2/dist/default-skin/default-skin.css" integrity="sha256-c0uckgykQ9v5k+IqViZOZKc47Jn7KQil4/MP3ySA3F8=" crossorigin="anonymous">'

  [params.counter.leancloud]  # Chinese leancloud visitor counter  # leancloud 计数器
    enable = true
    appId = "yp4nIF0OXyIMTEyjixb0p6w5-gzGzoHsz"
    appKey = "iooXBj18fhM6S4yonspGEspA"

  [params.social]
  a-email = "mailto:1@kqh.ac"
  d-facebook = "https://www.facebook.com/kujihhoe"
  g-github = "https://github.com/kujihhoe"
  i-zhihu = "https://www.zhihu.com/people/ke-qi-han/activities"
  j-douban = "https://www.douban.com/people/kujihhoe/"
